[package]
name = "ffrost"
edition = "2021"
description = "simple program for calculating the total duration of a collection of media"
version = "1.0.0"
authors = ["fawn <fawn@envs.net>"]
license = "ISC"
repository = "https://github.com/fawni/ffrost"
